export const Modifiers = [
  'Command',
  'Cmd',
  'Control',
  'Ctrl',
  'CommandOrControl',
  'CmdOrCtrl',
  'Alt',
  'Option',
  'AltGr',
  'Shift',
  'Super',
];

export const ModifiersReg = new RegExp(`^(${Modifiers.join('|')})$`);

export const KeyCodesReg =
  /^([0-9A-Z)!@#$%^&*(:+<_>?~{|}";=,\-./`[\\\]']|F1*[1-9]|F10|F2[0-4]|Plus|Space|Tab|Backspace|Delete|Insert|Return|Enter|Up|Down|Left|Right|Home|End|PageUp|PageDown|Escape|Esc|VolumeUp|VolumeDown|VolumeMute|MediaNextTrack|MediaPreviousTrack|MediaStop|MediaPlayPause|PrintScreen)$/;

export const KeyToCodeMap = Object.assign(Object.create(null) as {}, {
  // domkey
  'plus': 'Add',
  'space': 'Space',
  'tab': 'Tab',
  'backspace': 'Backspace',
  'delete': 'Delete',
  'insert': 'Insert',
  'return': 'Return',
  'enter': 'Return',
  'up': 'ArrowUp',
  'down': 'ArrowDown',
  'left': 'ArrowLeft',
  'right': 'ArrowRight',
  'home': 'Home',
  'end': 'End',
  'pageup': 'PageUp',
  'pagedown': 'PageDown',
  'escape': 'Escape',
  'esc': 'Escape',
  'volumeup': 'AudioVolumeUp',
  'volumedown': 'AudioVolumeDown',
  'volumemute': 'AudioVolumeMute',
  'medianexttrack': 'MediaTrackNext',
  'mediaprevioustrack': 'MediaTrackPrevious',
  'mediastop': 'MediaStop',
  'mediaplaypause': 'MediaPlayPause',
  'printscreen': 'PrintScreen',
  'f1': 'F1',
  'f2': 'F2',
  'f3': 'F3',
  'f4': 'F4',
  'f5': 'F5',
  'f6': 'F6',
  'f7': 'F7',
  'f8': 'F8',
  'f9': 'F9',
  'f10': 'F10',
  'f11': 'F11',
  'f12': 'F12',
  'f13': 'F13',
  'f14': 'F14',
  'f15': 'F15',
  'f16': 'F16',
  'f17': 'F17',
  'f18': 'F18',
  'f19': 'F19',
  'f20': 'F20',
  'f21': 'F21',
  'f22': 'F22',
  'f23': 'F23',
  'f24': 'F24',
  // virtualkey
  0: 'Digit0',
  1: 'Digit1',
  2: 'Digit2',
  3: 'Digit3',
  4: 'Digit4',
  5: 'Digit5',
  6: 'Digit6',
  7: 'Digit7',
  8: 'Digit8',
  9: 'Digit9',
  '-': 'Minus',
  '=': 'Equal',
  'q': 'KeyQ',
  'w': 'KeyW',
  'e': 'KeyE',
  'r': 'KeyR',
  't': 'KeyT',
  'y': 'KeyY',
  'u': 'KeyU',
  'i': 'KeyI',
  'o': 'KeyO',
  'p': 'KeyP',
  '[': 'BracketLeft',
  ']': 'BracketRight',
  'a': 'KeyA',
  's': 'KeyS',
  'd': 'KeyD',
  'f': 'KeyF',
  'g': 'KeyG',
  'h': 'KeyH',
  'j': 'KeyJ',
  'k': 'KeyK',
  'l': 'KeyL',
  ';': 'Semicolon',
  "'": 'Quote',
  '`': 'Backquote',
  '/': 'Backslash',
  'z': 'KeyZ',
  'x': 'KeyX',
  'c': 'KeyC',
  'v': 'KeyV',
  'b': 'KeyB',
  'n': 'KeyN',
  'm': 'KeyM',
  ',': 'Comma',
  '.': 'Period',
  '\\': 'Slash',
  ' ': 'Space',
});

export const IsMac = process.platform === 'darwin';
export const IsWin = process.platform === 'win32';
